# Generated by Django 4.2.5 on 2023-09-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='student_addresss',
            new_name='student_address',
        ),
    ]
