# Generated by Django 4.2.5 on 2023-09-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_catogory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.catogory')),
            ],
        ),
    ]
